version: 2

sources:
  - name: github_events
    database: neondb
    schema: "{{ var('source_schema', 'git_hub_events_ock') }}"
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: timestamp
    tables:
      - name: webhook_source_event
      - name: tracks

models:
  - name: gh_events_pull_requests
    description: "All PR events"
    columns:
      - name: pull_request
        description: "The PR data json"
        tests:
          - not_null
      - name: number
        description: "The PR number"
        tests:
          - not_null
      - name: repository
        description: "The repository to which this PR belongs to"
        tests:
          - not_null
      - name: action
        description: "The action taken on PR"
        tests:
          - not_null
      - name: sender
        description: "User who took took this action"
        tests:
          - not_null

  - name: gh_events_pull_requests_opened
    description: "All PR creation events"
    columns:
      - name: pull_request
        description: "The PR data json"
        tests:
          - not_null